
#define SHADOWS_ENABLED 1
#define NORMAL_MAP_ENABLED 1
//#define SCREEN_SPACE_REFLECTIONS_ENABLED 1
//#define METALLNESS_ENABLED 1
#define ANISATROPIC_ENABLED 1
#define SUBSURFACE_SCATTERING_ENABLED 1
#define AO_FROM_NORMALMAP_A 1
//#define METALLIC_FROM_BASE 1
//#define ROUGHTNESS_MAP_ENABLED 1
// #define TRANSPARENCY_ENABLED 1
#define TBN_ENABLED 1

#include "base3Dsurace.fsh"
